version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ezypayments-postgres
    environment:
      POSTGRES_DB: ezypayments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: [
      "postgres",
      "-c", "hba_file=/etc/postgresql/pg_hba.conf",
      "-c", "listen_addresses=*"
    ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ezypayments-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata: